### ISSUE TITLE
Show search tips

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#312] opened 2016-01-12 16:00 UTC
AA suggests 'a line under the bar saying search tips which popups up with boolean operators and examples'.

We should mock something up for prod2 for review before doing all of this.

**Comment by davidread** [comment] 2016-01-12 16:21
Duplicate of https://github.com/datagovuk/ckanext-dgu/issues/308

**Closed by davidread** 2016-01-12 16:21 UTC
