### ISSUE TITLE
Enable all solr operators

### ISSUE THREAD

**Issue by davidread** [datagovuk/ckanext-dgu#311] opened 2016-01-11 16:08 UTC
To do this there is a thing called 'solr_escape' which we can easily remove.

**Comment by rossjones** [comment] 2016-01-12 09:20
Is this a duplicate of #306?

**Comment by davidread** [comment] 2016-01-12 09:42
#306 is only concerned with the dash, but there are plenty of other operators in SOLR we can usefully enable, such as quoting and colon for per-field search. See also #308.

**Comment by rossjones** [comment] 2016-01-18 11:45
We should blog about the changes once this is done.

**Closed** 2016-01-18 15:24 UTC
Labels: in progress
