### ISSUE TITLE
Search indexing crash

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-dgu#303] opened 2016-01-08 14:02 UTC
When trying to run a full re-index, the following exception is thrown:

```
Indexing dataset 9530/260392016-01-08 12:57:42,550 ERROR [ckan.lib.search] Error while indexing dataset e28d08b5-3bc5-4c96-908a-fd10903c31db:
Traceback (most recent call last):
  File "/home/co/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/co/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 484, in command
    self.rebuild()
  File "/vagrant/src/ckan/ckan/lib/cli.py", line 556, in rebuild
    quiet=self.options.quiet)
  File "/vagrant/src/ckan/ckan/lib/search/__init__.py", line 199, in rebuild
    {'id': pkg_id}
  File "/vagrant/src/ckan/ckan/logic/__init__.py", line 425, in wrapped
    result = _action(context, data_dict, **kw)
  File "/vagrant/src/ckan/ckan/logic/action/get.py", line 925, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/vagrant/src/ckan/ckan/lib/dictization/model_dictize.py", line 212, in package_dictize
    raise logic.NotFound
ckan.logic.NotFound
```

**Comment by davidread** [comment] 2016-02-11 16:25
This was caused by #293, for which the changes I made appear to have solved the problem, so closing this.

**Closed by davidread** 2016-02-11 16:25 UTC
Labels: in progress
